/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sinhvien;

/**
 *
 * @author chessy
 */
public class GUI_SinhVien extends javax.swing.JPanel {

    /**
     * Creates new form GUI_SinhVien
     */
    public GUI_SinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblJava = new javax.swing.JLabel();
        lblCSS = new javax.swing.JLabel();
        lblHTML = new javax.swing.JLabel();
        rbtnCNTT = new javax.swing.JRadioButton();
        rbtnKinhTe = new javax.swing.JRadioButton();
        txtMa = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        txtJava = new javax.swing.JTextField();
        txtHTML = new javax.swing.JTextField();
        txtCSS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDocFile = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Nghanh ");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("MaSV");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("HoTen");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Gioi tinh");

        lblJava.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblJava.setText("Java");

        lblCSS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblCSS.setText("CSS");

        lblHTML.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblHTML.setText("HTML");

        buttonGroup1.add(rbtnCNTT);
        rbtnCNTT.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbtnCNTT.setText("CNTT");
        rbtnCNTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCNTTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnKinhTe);
        rbtnKinhTe.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbtnKinhTe.setText("Kinh te");
        rbtnKinhTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKinhTeActionPerformed(evt);
            }
        });

        txtMa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnNam);
        rbtnNam.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbtnNam.setText("Nam");

        buttonGroup2.add(rbtnNu);
        rbtnNu.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbtnNu.setText("Nu");

        txtJava.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJavaActionPerformed(evt);
            }
        });

        txtHTML.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHTMLActionPerformed(evt);
            }
        });

        txtCSS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSSActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDocFile.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnDocFile.setText("Doc File");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnThem.setText("Them");

        btnUpdate.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCNTT)
                                .addGap(40, 40, 40)
                                .addComponent(rbtnKinhTe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHoTen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnNam)
                                .addGap(40, 40, 40)
                                .addComponent(rbtnNu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtJava))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCSS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHTML))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnDocFile)
                        .addGap(40, 40, 40)
                        .addComponent(btnThem)
                        .addGap(40, 40, 40)
                        .addComponent(btnUpdate)))
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnCNTT)
                            .addComponent(rbtnKinhTe))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHTML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDocFile)
                            .addComponent(btnThem)
                            .addComponent(btnUpdate))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJavaActionPerformed

    private void txtHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHTMLActionPerformed

    private void txtCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSSActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void rbtnKinhTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKinhTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnKinhTeActionPerformed

    private void rbtnCNTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCNTTActionPerformed
        lblJava.setText("NLKT");
        lblCSS.setText("Marketing");
        lblHTML.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCNTTActionPerformed
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SinhVien().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCSS;
    private javax.swing.JLabel lblHTML;
    private javax.swing.JLabel lblJava;
    private javax.swing.JRadioButton rbtnCNTT;
    private javax.swing.JRadioButton rbtnKinhTe;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTextField txtCSS;
    private javax.swing.JTextField txtHTML;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
